# Generated by Django 3.2.3 on 2021-05-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210529_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pic.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pic.jpeg', null=True, upload_to=''),
        ),
    ]
