# Generated by Django 3.2.3 on 2021-05-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210529_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default='profile_pic.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(default='profile_pic.jpeg', upload_to=''),
        ),
    ]
