# Generated by Django 3.2.3 on 2021-06-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210529_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='language',
        ),
    ]
