# Generated by Django 3.2.3 on 2021-06-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number_of_students',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='recording_link',
            field=models.TextField(null=True),
        ),
    ]
