# Generated by Django 3.2.3 on 2021-06-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20210602_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='recording_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
