# Generated by Django 3.2.3 on 2021-06-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_lesson_recording_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
