# Generated by Django 3.2.3 on 2021-06-02 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20210602_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.group'),
        ),
    ]
