# Generated by Django 3.2.3 on 2021-06-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_assignment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
